### ISSUE TITLE
Missing Library

### ISSUE THREAD

**Issue by vbbalaji** [adameat/MaximWire#2]
Hello
Im trying to use this on a Nano and got this error. Please ignore the rest of the code as Im trying to interface the Arduino with a NodeMCU

Arduino\libraries\MaximWire\src\HAL\NRF52840.cpp:2:10: fatal error: nrf_gpio.h: No such file or directory
 #include <nrf_gpio.h>
          ^~~~~~~~~~~~
compilation terminated.
exit status 1
Error compiling for board Arduino Nano.

Here is my code:
`
#include <Wire.h>
#include <Servo.h>
#include <stdlib.h>

#include <MaximWire.h>

#define PIN_BUS 2

MaximWire::Bus bus(PIN_BUS);
MaximWire::DS18B20 poolTemp;

Servo myServo;

int SERVOM = A0;
int ONEBUS = 2;

void setup() {
 Wire.begin(8);                /* join i2c bus with address 8 */
 Wire.onReceive(receiveEvent); /* register receive event */
 Wire.onRequest(requestEvent); /* register request event */
 Serial.begin(115200);           /* start serial for debug */
 myServo.attach(SERVOM);
 myServo.write(0);
}

void loop() {
  poolTemp.requestTemperatures();
  float temperatureC = poolTemp.getTempCByIndex(0);
  float temperatureF = poolTemp.getTempFByIndex(0);
  Serial.print("Temperature: ");
  Serial.print(temperatureC);
  Serial.print("ºC    ");
  Serial.print(temperatureF);
  Serial.println("ºF");
  delay(1000);
}

char inVal[10];

// function that executes whenever data is received from master
void receiveEvent(int howMany) {
  int i = 0;
 while (0 <Wire.available()) {
    char c = Wire.read();      /* receive byte as a character */
    Serial.print(c);           /* print the character */
    inVal[i] = c;
    inVal[i+1] = '\0';
    i++;
}
 int sv = atoi(inVal);
 myServo.write(sv);
 Serial.println();             /* to newline */
 Serial.print("Received:");
 Serial.print(inVal);
 Serial.println("]");
}

// function that executes whenever data is requested from master
void requestEvent() {
 Wire.write("Hello NodeMCU");  /*send string on request */
}
`

**Comment by IainM22** [comment]
I'm having the same problem when trying to compile the code.

**Comment by IainM22** [comment]
^ My mistake, this library is for the Nano 33 BLE and I was trying to compile it for my Nano 33 IoT

**Comment by Opalo** [comment]
So it seems that this issue might be closed.
