### ISSUE TITLE
undefined reference to digitalPinToPinName(unsigned char)

### ISSUE THREAD

**Issue by bhartung** [adameat/MaximWire#4]
I was hoping to use this library to get my temp probe working, but I'm getting a compiler error.  Any help is appreciated.

`sketch/nano_probe_temp_sensor.ino.cpp.o: In function _GLOBAL__sub_I__ZN9MaximWire7DS18B2014GetTemperatureIsEET_RNS_3BusE:
/sketchbooks/libraries/MaximWire/src/HAL/NRF52840.h:40: undefined reference to digitalPinToPinName(unsigned char)
collect2: error: ld returned 1 exit status
exit status 1
Error compiling for board Arduino Nano 33 BLE.
`

The code is identical to your AnyDevice.ino file except I'm using pin 2.

**Comment by bhartung** [comment]
I got this to compile by including Wire.h also, and the probe is ready correctly.

#include <Wire.h>
#include <MaximWire.h>

**Comment by kmr4** [comment]
I am having  the same issue.  The examples for MaximWire fail  to compile on Nano 33 BLE (see below).   Any help to remedy would be greatly appreciated!!

Arduino: 1.8.13 (Windows Store 1.8.42.0) (Windows 10), Board: "Arduino Nano 33 BLE"
sketch\DiscoveryDevices.ino.cpp.o: In function `_GLOBAL__sub_I__ZN9MaximWire7DS18B2014GetTemperatureIsEET_RNS_3BusE':

C:\Users\OneDrive\Arduino\libraries\MaximWire\src/HAL/NRF52840.h:40: undefined reference to `digitalPinToPinName(unsigned char)'

collect2.exe: error: ld returned 1 exit status
exit status 1
Error compiling for board Arduino Nano 33 BLE.

**Comment by kmr4** [comment]
I also tried by installing the inclusion of <Wire.h>. Even though its not an installed library in my IDE, it worked. I have no idea why, but now I can move forward    Thanks BHartung!

**Comment by adameat** [comment]
> I was hoping to use this library to get my temp probe working, but I'm getting a compiler error. Any help is appreciated.
> 
> `sketch/nano_probe_temp_sensor.ino.cpp.o: In function _GLOBAL__sub_I__ZN9MaximWire7DS18B2014GetTemperatureIsEET_RNS_3BusE: /sketchbooks/libraries/MaximWire/src/HAL/NRF52840.h:40: undefined reference to digitalPinToPinName(unsigned char) collect2: error: ld returned 1 exit status exit status 1 Error compiling for board Arduino Nano 33 BLE. `
> 
> The code is identical to your AnyDevice.ino file except I'm using pin 2.

Sorry, I can't reproduce it by using neither Arudino IDE or PlatformIO.
Can you tell me, what is your environment?

**Comment by kmr4** [comment]
Iam using  Arduino: 1.8.13  IDE (Windows Store 1.8.42.0) (Windows 10), Board: "Arduino Nano 33 BLE"

You need to also include the wire.h library 
#include <Wire.h>
It solved my compile error

**Comment by adameat** [comment]
I'm sorry, but I still can't reproduce this issue. Probably it could be because of wrong includes in your main .ino file.
Anyway, I have moved this call to cpp file, it should mitigate the issue.

**Comment by FiorelaMF** [comment]
I have the same error using an HC-SR04 sensor (no libraries) with my Arduino Nano 33 BLE. Does someone know how could I fix this?
